# Generated by Django 4.1.7 on 2023-03-28 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions_listing',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auctions_listing',
            name='current',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='auctions_listing',
            name='winner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
