# Generated by Django 4.1.7 on 2023-03-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctions_listing_active_auctions_listing_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions_listing',
            name='current',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
