# Generated by Django 4.1.7 on 2023-03-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctions_listing_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions_listing',
            name='current',
            field=models.IntegerField(default=None),
        ),
    ]
